#!/bin/bash

# Name: auto-knight
# Description: This script automatically changes the global theme of KDE Plasma based on the time of day.
# It utilizes KDE's built-in Night Light feature to determine whether it is day or night.
# The script is intended to be run on startup.
# Author: Dmitriy Safiullin
# Date: 20204.03.16

# Theme and command settings
light_theme="org.kde.breezetwilight.desktop"
dark_theme="org.kde.breezedark.desktop"
change_theme_command="plasma-apply-lookandfeel -a"

# Function to set the theme and update state
set_theme() {
    $change_theme_command "$1"  # Apply the specified theme
    last_theme="$1"  # Update the last theme variable
}

# Gets current daylight status
is_daylight() {
    daylight_status=$(qdbus6 org.kde.KWin /org/kde/KWin/NightLight org.kde.KWin.NightLight.daylight)
    [[ "$daylight_status" == "true" ]]
}

# Initialize the theme based on the current daylight status
if is_daylight; then
    set_theme "$light_theme"  # Set the light theme
else
    set_theme "$dark_theme"  # Set the dark theme
fi

# Monitor changes in daylight status and update the theme accordingly
dbus-monitor --session "type='signal',interface='org.freedesktop.DBus.Properties', member='PropertiesChanged', path='/org/kde/KWin/NightLight'" |
    grep --line-buffered "daylight" |
    while read -r line; do
        if is_daylight; then
            [[ "$last_theme" != "$light_theme" ]] && set_theme "$light_theme"  # Set the light theme if it needs to be changed
        else
            [[ "$last_theme" != "$dark_theme" ]] && set_theme "$dark_theme"  # Set the dark theme if it needs to be changed
        fi
    done
