#!/bin/bash

# Name: auto-knight
# Description: This script automatically changes the global theme of
# KDE Plasma based on the time of day. It utilizes KDE's built-in
# Night Light feature to determine whether it is day or night.
# The script is intended to be autostarted.
# Author: Dmitriy Safiullin
# Date: 2024.03.16

# theme and command settings
LIGHT_THEME="org.kde.breeze.desktop"
DARK_THEME="org.kde.breezedark.desktop"
CHANGE_THEME_COMMAND="plasma-apply-lookandfeel -a"

# sets theme and updates state
set_theme() {
    $CHANGE_THEME_COMMAND "$1"
    LAST_THEME="$1"
}

# retrieves current daylight status
is_daylight() {
    local daylight_status
    daylight_status=$(qdbus org.kde.KWin /org/kde/KWin/NightLight \
        org.kde.KWin.NightLight.daylight)
    [[ "$daylight_status" == "true" ]]
}

# initializes the theme based on the current daylight status
initialize_theme() {
    if is_daylight; then
        set_theme "$LIGHT_THEME"
    else
        set_theme "$DARK_THEME"
    fi
}

# monitors changes in daylight status and updates the theme accordingly
monitor_daylight_changes() {
    dbus-monitor --session \
        "type='signal',interface='org.freedesktop.DBus.Properties', \
        member='PropertiesChanged', path='/org/kde/KWin/NightLight'" |
        grep --line-buffered "daylight" |
        while read -r line; do
            if is_daylight; then
                [[ "$LAST_THEME" != "$LIGHT_THEME" ]] && set_theme "$LIGHT_THEME"
            else
                [[ "$LAST_THEME" != "$DARK_THEME" ]] && set_theme "$DARK_THEME"
            fi
        done
}

initialize_theme
monitor_daylight_changes
